Update patch set 3
Patch Set 3:

The error comes from:
Fatal error: Uncaught exception 'InvalidArgumentException' with message 'Key "CanonicalNamespaceNames" not found in input sources' in /workspace/src/includes/config/ServiceOptions.php:52
Stack trace:
#0 /workspace/src/includes/ServiceWiring.php(439): MediaWiki\Config\ServiceOptions->__construct()
#1 /workspace/src/includes/libs/services/ServiceContainer.php(459): Closure$#41()
#2 /workspace/src/includes/libs/services/ServiceContainer.php(427): Wikimedia\Services\ServiceContainer->createService()
#3 /workspace/src/includes/MediaWikiServices.php(751): Wikimedia\Services\ServiceContainer->getService()
#4 /workspace/src/includes/MWNamespace.php(238): MediaWiki\MediaWikiServices->getNamespaceInfo()
#5 /workspace/src/extensions/ArticleRatings/ArticleRatingsHooks.php(10): MWNamespace::getContentNamespaces()
#6 /workspace/src/includes/registration/ExtensionRegistry.php(441): AreHooks::onRegisterExtension()
#7 /workspace/src/includes/registration/ExtensionRegistry.php(188): ExtensionRegistry->exportExtractedData()
#8 /workspace/src/includes/Setup.php(132): ExtensionRegistry->loadFromQueue()
#9 /workspace/src/maintenance/doMaintenance.php(83): include()
#10 /workspace/src/maintenance/update.php(277): include()
#11 {main}

which is completely unrelated...

Patch-set: 3
Reviewer: DannyS712 <6729@e9e9afe9-4712-486d-8885-f54b72dd1951>